//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpencerGifts.Translate.Plugin.TLog.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TlogResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TlogResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpencerGifts.Translate.Plugin.TLog.Properties.TlogResource", typeof(TlogResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -------------------------------Translate Complete-------------------------------.
        /// </summary>
        internal static string AppDone {
            get {
                return ResourceManager.GetString("AppDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program running longer than expected with no work to do.  Terminating Program..
        /// </summary>
        internal static string AppTimeOut {
            get {
                return ResourceManager.GetString("AppTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Done File in {0} .
        /// </summary>
        internal static string CreatingDoneFile {
            get {
                return ResourceManager.GetString("CreatingDoneFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable To Create Done File {0} .
        /// </summary>
        internal static string DoneFileError {
            get {
                return ResourceManager.GetString("DoneFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is valid.
        /// </summary>
        internal static string FileIsValid {
            get {
                return ResourceManager.GetString("FileIsValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt was made to retrieve files from {0} and was not successful.  Please check to make sure the path is valid and exists..
        /// </summary>
        internal static string InvalidDirectory {
            get {
                return ResourceManager.GetString("InvalidDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} is not valid. Skipping Translate.
        /// </summary>
        internal static string InvalidFile {
            get {
                return ResourceManager.GetString("InvalidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving File to bad log location {0}.
        /// </summary>
        internal static string MovingBadTLog {
            get {
                return ResourceManager.GetString("MovingBadTLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consignment Store File Not Found.  Translate Cannot Continue.
        /// </summary>
        internal static string NoConsignmentStoreFile {
            get {
                return ResourceManager.GetString("NoConsignmentStoreFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Files To Translate.
        /// </summary>
        internal static string NoFiles {
            get {
                return ResourceManager.GetString("NoFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create output directory {0}: {1}.
        /// </summary>
        internal static string OutputDirError {
            get {
                return ResourceManager.GetString("OutputDirError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renaming {0} to {1} .
        /// </summary>
        internal static string RenameDir {
            get {
                return ResourceManager.GetString("RenameDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable To Rename Directory {0} .
        /// </summary>
        internal static string RenameDirError {
            get {
                return ResourceManager.GetString("RenameDirError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate Completed for {0} {1}.
        /// </summary>
        internal static string TranslateComplete {
            get {
                return ResourceManager.GetString("TranslateComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -------------------------------Translate Started-------------------------------.
        /// </summary>
        internal static string TranslateStarted {
            get {
                return ResourceManager.GetString("TranslateStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translating File {0}.
        /// </summary>
        internal static string TranslatingFile {
            get {
                return ResourceManager.GetString("TranslatingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled Exception while translating file {0}: {1}.
        /// </summary>
        internal static string UnHandledException {
            get {
                return ResourceManager.GetString("UnHandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating File {0}.
        /// </summary>
        internal static string ValidateFile {
            get {
                return ResourceManager.GetString("ValidateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check to make sure {0} is valid.
        /// </summary>
        internal static string ValidPathCheck {
            get {
                return ResourceManager.GetString("ValidPathCheck", resourceCulture);
            }
        }
    }
}
